#!/usr/bin/env bash
rm -f /usr/share/applications/memority-core.desktop
rm -f /usr/share/applications/memority-ui.desktop
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ] ; then
update-menus
fi
